services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: corporate_is
      POSTGRES_USER: corporate_is
      POSTGRES_PASSWORD: corporate_is_password
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
